In [ ]:
%load_ext autoreload
%autoreload 2

In [4]:
import pandas as pd
import numpy as np
import csrar
from sklearn.model_selection import train_test_split

In [50]:
a = [-0.0301193837409, 0.000457581561074, 0.0242727083637, -0.0595909790806, 0.0288904326627,
     0.00644182319611,0.0023434551013, -0.0286107235616,0.0077272104507, 0.00737929719405]
np.mean(a)

-0.0040808577853465996

In [116]:
a = [np.array([1,2,3])]
for lol in a:
    print(lol)

[1 2 3]


In [51]:
def gini(array):
    array = array.flatten()
    if np.amin(array) < 0:
        array -= np.amin(array)
    array += 0.0000001
    array = np.sort(array)
    index = np.arange(1,array.shape[0]+1)
    n = array.shape[0]
    return ((np.sum((2 * index - n  - 1) * array)) / (n * np.sum(array)))

In [87]:
dist = np.array([1/4] * 4)
while gini(dist) < 0.6:
    dist = np.random.rand(4)
dist

array([ 0.85196203,  0.24442307,  0.00105643,  0.01633102])

In [102]:
binary_div_df = pd.DataFrame(columns=['0.0', '1.0', '2.0'], index=[0]).fillna(0)
binary_div_df2 = pd.DataFrame(columns=['0.0', '1.0', '2.0'], index=[0]).fillna(0.5)
test = {
    'a': binary_div_df,
    'b': binary_div_df2
}

In [122]:
for i in binary_div_df['0.0'].iteritems():
    print(i.column)

AttributeError: 'tuple' object has no attribute 'column'

In [113]:
a, _ = ('2', '3')
_

'3'

In [104]:
indices = [tuple(index) for index in test]
scores = [score for index, score in test.items()]
new_relevancies = pd.DataFrame(data=scores, index=indices)
new_relevancies

0
(a,)     0.0  1.0  2.0
0    0    0    0
(b,)     0.0  1.0  2.0
0  0.5  0.5  0.5

In [109]:
new_relevancies[0][('a',)]

0.0  1.0  2.0
0    0    0    0

In [97]:
dist

array([ 0.76493359,  0.21945511,  0.00094851,  0.01466279])

In [2]:
data = pd.read_csv('../data/Injector_Median100k.csv')

In [10]:
X = data.drop('Col174', axis=1)
y = data['Col174']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=5)

In [11]:
X_test

0         1         2         3         4         5         6   \
24166 -1.132954 -0.529332 -2.280111  0.828081 -1.266780 -2.409994  2.445317   
42699  0.051053  1.057167 -0.445697  0.660821 -0.321692  0.822010 -0.306635   
15927  0.300304  1.235321  0.109885  1.854542  0.583341  2.236067 -1.667990   
7473  -0.835659  0.541545  2.082648  0.381698 -0.454977  1.997699 -2.174094   
5070  -1.527724  1.769555  0.576986 -0.824658  0.708849  1.047867 -0.525502   
33926 -0.656407 -2.976683  0.280318 -0.019446 -1.501808 -2.157457  1.035022   
21409 -0.379643  0.513969 -0.921569 -2.130628  0.874219 -1.385711  1.458493   
9495   0.168654  0.343844 -0.108644 -1.875611  1.744207 -0.708428  0.838252   
16235  0.934957  0.372184 -0.168887  0.923648 -0.624599  0.976759 -0.616142   
35747 -0.217729  0.634640  0.487273  0.200610 -1.182167  0.576834 -0.693506   
46288  2.072761  0.665912  1.139228 -0.406565 -1.354836  0.972402 -1.566761   
13560 -1.077186  0.143189  1.405300  0.538192  1.524841  1.622361 -1.295567   
29644  0.629522  1.430145  0.161626 -0.181094  0.495560  1.009825 -0.622896   
28992  0.617123 -0.709774  1.190145  0.328224  0.430198  0.771672 -1.249733   
35350  0.382014 -0.043610 -0.428664  0.976635  0.792561  0.576025 -0.109837   
43077  1.184952  0.900746 -1.241378  1.063928 -0.153502  0.734136 -0.147722   
35757 -0.686160 -0.746328  1.742482  0.876808  2.445113  1.797676 -1.668827   
24106 -0.961667  0.001473 -1.537221 -0.926940  0.886428 -1.679943  2.041991   
26555 -1.349637  0.686134  1.641241  0.044311  1.225187  1.434631 -1.219307   
22478 -0.210119  0.264214  0.039063 -0.077661 -1.729615 -0.537718  0.010041   
1951  -2.152237  1.924168 -0.327413 -0.163369 -1.147157  0.360072 -0.154037   
29145  0.427744  0.207498  0.614365 -2.139268 -0.781262 -1.144281  0.125677   
33373 -0.344942  0.538041 -0.179244 -1.345150 -1.712291 -1.149999  0.591265   
10043 -0.001200 -0.339499  1.240736  1.643396  0.420302  1.761333 -1.718929   
21988  0.320316  0.348243 -1.414974  0.864345 -1.704417 -0.663580  0.895239   
37116  1.695848 -1.305560 -0.167392  1.286249  0.986880  0.507384 -0.220837   
15760 -0.765195  0.750833  1.138372 -0.755454 -0.113551  0.259097 -0.494839   
48939  2.145244 -0.228158  0.716999  1.380607 -0.719749  1.316872 -1.411423   
29761  0.094354 -1.234602 -0.530400 -0.981505  0.610907 -1.443608  1.409266   
3702   0.088288  0.020307  1.371575 -0.766338  1.049645  0.853817 -0.892518   
...         ...       ...       ...       ...       ...       ...       ...   
6776  -1.728733  0.705561  0.356636 -1.345204 -0.146420 -0.608146  0.404948   
45778 -1.602729 -1.377962  1.066880 -1.057718  0.197043 -1.261591  0.552481   
48938  0.613617 -0.701196 -0.345405 -0.308679  1.214588 -0.489399  0.346465   
32893  2.094830 -0.818321  0.299142  0.454690  0.366844  0.093175 -0.476180   
41205  1.161570  0.556562 -0.046044 -0.704344  1.161981  0.274804  0.042040   
35316 -0.738184 -0.979425 -0.063759 -0.171548  1.697839 -0.550116  0.672876   
23517 -0.623746  0.513236  0.615221  0.878907  0.670258  1.359927 -1.352846   
30555  0.129493  0.077563  0.024704 -2.208244  0.052141 -1.437344  0.850202   
42846 -0.267781 -0.257309 -0.040751  0.221674 -0.677453 -0.215137  0.127825   
12294  0.365243  0.411186 -0.583382 -2.530445 -1.901641 -2.115818  1.432459   
6515   0.806328 -1.792068 -0.365371 -2.191827 -1.053690 -3.125303  1.867808   
28951  1.289828  1.016248 -1.290872 -0.930182 -0.037441 -0.703731  0.780612   
33175 -1.816250  1.033012  0.541161  0.586694  0.404598  1.382395 -0.744737   
28608 -0.210318  2.522772  1.241508  1.632014 -0.424316  3.961414 -3.025979   
25327  1.801356  0.210682  0.349412  0.799560  0.255603  1.427280 -1.278756   
10943  0.396698 -0.922206  0.463048 -0.312719 -0.618536 -0.647234 -0.118673   
6269   0.156219  2.083855  0.493973 -0.585030  2.209349  1.927059 -1.242466   
24099 -0.821824 -0.090092  1.110707  0.091105  0.364888  0.739670 -0.849963   
23394  0.025718 -0.053296 -0.634326  0.903412 -0.076133 -0.1249

In [3]:
rar_data = pd.concat([X_train, y_train], axis=1)

In [5]:
data2 = pd.DataFrame(data=np.arange(len(rar_data)), index=rar_data.index)

In [8]:
len(rar_data)

60123

In [4]:
target = 'Col174'
rar = csrar.rar.RaR(rar_data)


In [ ]:
rar.run(target, k=5, runs=200)

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier()
clf.fit(data.drop('Col174', axis=1), data['Col174'])


In [ ]:
ranking = []
for index, importance in enumerate(clf.feature_importances_):
    ranking.append((data.columns[index], importance))
ranking.sort(key=lambda r: r[1], reverse=True)
for (index, rank) in enumerate(ranking):
        print('{}. {} with a score of {}'.format(index + 1, rank[0], rank[1]))