In [ ]:
%load_ext autoreload
%autoreload 2

In [219]:
def gini(array):
    array = array.flatten()
    if np.amin(array) < 0:
        array -= np.amin(array)
    array += 0.0000001
    array = np.sort(array)
    index = np.arange(1,array.shape[0]+1)
    n = array.shape[0]
    return ((np.sum((2 * index - n  - 1) * array)) / (n * np.sum(array)))

In [232]:
gini(np.array([0.5, 0.45, 0.05]))

0.29999991000002696

In [189]:
import pandas as pd
import numpy as np
import wrar
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_svmlight_file

In [213]:
datas = []
for i in range(1, 11):
    X, y = load_svmlight_file('../data/gas_sensor/batch'+ str(i) +'.dat')
    data = pd.SparseDataFrame(X)
    # print(len(np.unique(data.isnull())))
    data = data.to_dense()
    data[128] = y
    datas.append(data)
data = pd.concat(datas).reset_index(drop=True)
data

1
1
1
1
1
1
1
1
1
1


0          1          2          3           4          5    \
0       15596.1621   1.868245   2.371604   2.803678    7.512213  -2.739388   
1       26402.0704   2.532401   5.411209   6.509906    7.658469  -4.722217   
2       42103.5820   3.454189   8.198175  10.508439   11.611003  -7.668313   
3       42825.9883   3.451192  12.113940  16.266853   39.910056  -7.849409   
4       58151.1757   4.194839  11.455096  15.715298   17.654915 -11.083364   
5       79872.1308   5.553595  18.690482  27.191770   28.636972 -15.054684   
6       94981.5859   5.872932  22.318174  32.673187   34.308656 -18.198780   
7      108075.6269   6.064713  25.660255  38.059268   40.191974 -21.472657   
8      121315.7675   7.118364  28.686061  42.979381   45.482180 -23.152346   
9      133600.9805   7.806088  30.785557  46.897557   49.198760 -25.285772   
10     143388.4375   8.108682  32.719714  52.804172   56.085335 -27.101796   
11     153219.6758   8.550419  35.069405  59.010483   63.362733 -28.818326   
12     163000.9179   8.876758  37.560191  64.591719   67.888394 -30.391950   
13     171024.1953   9.242443  38.866519  68.239326   72.181715 -31.302355   
14      18492.2539   2.034586   2.791746   3.278644    4.758722  -3.070496   
15      32765.4004   2.830663   6.417207   7.910386    8.781465  -5.702962   
16      43883.3906   3.509948   9.549415  12.454272   13.509733  -7.876028   
17      53080.8145   3.949591  12.246095  16.872418   18.075721  -9.799573   
18      61543.6621   4.556067  14.722279  20.563837   21.799533 -11.367965   
19      80026.4473   5.490876  19.383897  28.271656   29.738304 -15.141047   
20      96025.6778   6.449523  23.062255  33.883861   35.606689 -18.175386   
21     109113.2774   7.177430  26.516047  39.590805   41.628144 -20.616577   
22     121232.4023   7.788830  28.828684  42.078983   43.842409 -22.825289   
23     132692.5859   8.381296  31.543339  47.088175   49.573256 -25.067681   
24     142473.4082   8.592894  33.955859  51.869412   55.067308 -26.924829   
25     151933.4667   9.025219  35.490090  55.857809   58.855086 -28.252755   
26     161261.5644   9.454960  37.236627  60.857386   64.016158 -29.745605   
27     170865.1113  10.083784  39.174547  63.780167   66.550620 -31.145867   
28      17503.5586   1.956871   2.574029   2.998929    3.811139  -2.913632   
29      32189.4804   2.921596   6.219521   9.009070    8.688272  -5.440235   
...            ...        ...        ...        ...         ...        ...   
13880   11228.4785   1.620900   2.645300   4.015000    8.233300  -2.523700   
13881   97478.6689   8.544100  21.612100  27.892700   38.717100 -15.733300   
13882   20725.9082   2.140100   4.783400   6.417100   11.629500  -4.400600   
13883  224957.5410  17.806400  57.675200  81.185800  108.900300 -36.624500   
13884   36837.1914   2.913000   9.066300  12.322000   27.266300  -7.628400   
13885  155490.6670  12.536500  36.957100  50.395800   65.585700 -25.605700   
13886    1109.1582   1.059100   1.176200   2.274300    6.626600  -0.703430   
13887   31197.7031   3.369000   4.742800   5.737700    8.911100  -4.184100   
13888   42534.9238   3.307100  10.978900  14.544900   21.055100  -8.634600   
13889  192391.5088  15.758200  47.980100  67.288200   83.980800 -30.861000   
13890   29943.6289   2.579000   7.024500   9.257000   15.949800  -6.302600   
13891  243262.0205  19.629500  63.515000  92.222500  114.886400 -37.896800   
13892   10485.9453   1.551500   2.588300   3.715600    7.931500  -2.510700   
13893   98995.3398   8.682800  21.510600  27.539400   39.760500 -15.781600   
13894   21695.2930   2.186000   4.929200   6.468500   10.362600  -4.525600   
13895  209189.9550  17.639800  54.442900  78.065900  108.504900 -33.847200   
13896   34649.0723   2.866800   8.239200  10.759900   15.889300  -7.039100   
13897  146183.3066  12.467900  35.224600  48.314500   64.450100 -23.238200   
13898   11108.0664   1.617500   2.618700   3.872800    7.479500  -2.478500   
13899   97450.8604   8.898100  21.256

In [218]:
np.unique(data[128], return_counts=True)[1] / len(data)

array([ 0.18439971,  0.21035226,  0.11797268,  0.13918045,  0.21631919,
        0.1317757 ])

In [207]:
type(y)

numpy.ndarray

In [50]:
a = [-0.0301193837409, 0.000457581561074, 0.0242727083637, -0.0595909790806, 0.0288904326627,
     0.00644182319611,0.0023434551013, -0.0286107235616,0.0077272104507, 0.00737929719405]
np.mean(a)

-0.0040808577853465996

In [116]:
a = [np.array([1,2,3])]
for lol in a:
    print(lol)

[1 2 3]


In [164]:
import arff
file = open('../data/6_wrar/6_wrar_1.arff', 'r')
dataset = arff.load(file)
file.close()
data = pd.DataFrame(dataset['data'])

In [165]:
gini(np.unique(data[80], return_counts=True)[1] / len(data))

0.6099996950001525

In [183]:
dist = np.array([1/10] * 10)
while gini(dist) < 0.4:
    dist = np.random.rand(10)
dist /= sum(dist)
gini(dist)

0.44651368751016107

In [187]:
dist

array([ 0.08492552,  0.16134044,  0.24345094,  0.23649193,  0.04297278,
        0.04374258,  0.0240011 ,  0.03437554,  0.11648754,  0.01221163])

In [155]:
dist

array([ 0.07469263,  0.38725803,  0.09925534,  0.06935828,  0.36943572])

In [102]:
binary_div_df = pd.DataFrame(columns=['0.0', '1.0', '2.0'], index=[0]).fillna(0)
binary_div_df2 = pd.DataFrame(columns=['0.0', '1.0', '2.0'], index=[0]).fillna(0.5)
test = {
    'a': binary_div_df,
    'b': binary_div_df2
}

In [122]:
for i in binary_div_df['0.0'].iteritems():
    print(i.column)

AttributeError: 'tuple' object has no attribute 'column'

In [113]:
a, _ = ('2', '3')
_

'3'

In [104]:
indices = [tuple(index) for index in test]
scores = [score for index, score in test.items()]
new_relevancies = pd.DataFrame(data=scores, index=indices)
new_relevancies

0
(a,)     0.0  1.0  2.0
0    0    0    0
(b,)     0.0  1.0  2.0
0  0.5  0.5  0.5

In [109]:
new_relevancies[0][('a',)]

0.0  1.0  2.0
0    0    0    0

In [97]:
dist

array([ 0.76493359,  0.21945511,  0.00094851,  0.01466279])

In [2]:
data = pd.read_csv('../data/Injector_Median100k.csv')

In [10]:
X = data.drop('Col174', axis=1)
y = data['Col174']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=5)

In [11]:
X_test

0         1         2         3         4         5         6   \
24166 -1.132954 -0.529332 -2.280111  0.828081 -1.266780 -2.409994  2.445317   
42699  0.051053  1.057167 -0.445697  0.660821 -0.321692  0.822010 -0.306635   
15927  0.300304  1.235321  0.109885  1.854542  0.583341  2.236067 -1.667990   
7473  -0.835659  0.541545  2.082648  0.381698 -0.454977  1.997699 -2.174094   
5070  -1.527724  1.769555  0.576986 -0.824658  0.708849  1.047867 -0.525502   
33926 -0.656407 -2.976683  0.280318 -0.019446 -1.501808 -2.157457  1.035022   
21409 -0.379643  0.513969 -0.921569 -2.130628  0.874219 -1.385711  1.458493   
9495   0.168654  0.343844 -0.108644 -1.875611  1.744207 -0.708428  0.838252   
16235  0.934957  0.372184 -0.168887  0.923648 -0.624599  0.976759 -0.616142   
35747 -0.217729  0.634640  0.487273  0.200610 -1.182167  0.576834 -0.693506   
46288  2.072761  0.665912  1.139228 -0.406565 -1.354836  0.972402 -1.566761   
13560 -1.077186  0.143189  1.405300  0.538192  1.524841  1.622361 -1.295567   
29644  0.629522  1.430145  0.161626 -0.181094  0.495560  1.009825 -0.622896   
28992  0.617123 -0.709774  1.190145  0.328224  0.430198  0.771672 -1.249733   
35350  0.382014 -0.043610 -0.428664  0.976635  0.792561  0.576025 -0.109837   
43077  1.184952  0.900746 -1.241378  1.063928 -0.153502  0.734136 -0.147722   
35757 -0.686160 -0.746328  1.742482  0.876808  2.445113  1.797676 -1.668827   
24106 -0.961667  0.001473 -1.537221 -0.926940  0.886428 -1.679943  2.041991   
26555 -1.349637  0.686134  1.641241  0.044311  1.225187  1.434631 -1.219307   
22478 -0.210119  0.264214  0.039063 -0.077661 -1.729615 -0.537718  0.010041   
1951  -2.152237  1.924168 -0.327413 -0.163369 -1.147157  0.360072 -0.154037   
29145  0.427744  0.207498  0.614365 -2.139268 -0.781262 -1.144281  0.125677   
33373 -0.344942  0.538041 -0.179244 -1.345150 -1.712291 -1.149999  0.591265   
10043 -0.001200 -0.339499  1.240736  1.643396  0.420302  1.761333 -1.718929   
21988  0.320316  0.348243 -1.414974  0.864345 -1.704417 -0.663580  0.895239   
37116  1.695848 -1.305560 -0.167392  1.286249  0.986880  0.507384 -0.220837   
15760 -0.765195  0.750833  1.138372 -0.755454 -0.113551  0.259097 -0.494839   
48939  2.145244 -0.228158  0.716999  1.380607 -0.719749  1.316872 -1.411423   
29761  0.094354 -1.234602 -0.530400 -0.981505  0.610907 -1.443608  1.409266   
3702   0.088288  0.020307  1.371575 -0.766338  1.049645  0.853817 -0.892518   
...         ...       ...       ...       ...       ...       ...       ...   
6776  -1.728733  0.705561  0.356636 -1.345204 -0.146420 -0.608146  0.404948   
45778 -1.602729 -1.377962  1.066880 -1.057718  0.197043 -1.261591  0.552481   
48938  0.613617 -0.701196 -0.345405 -0.308679  1.214588 -0.489399  0.346465   
32893  2.094830 -0.818321  0.299142  0.454690  0.366844  0.093175 -0.476180   
41205  1.161570  0.556562 -0.046044 -0.704344  1.161981  0.274804  0.042040   
35316 -0.738184 -0.979425 -0.063759 -0.171548  1.697839 -0.550116  0.672876   
23517 -0.623746  0.513236  0.615221  0.878907  0.670258  1.359927 -1.352846   
30555  0.129493  0.077563  0.024704 -2.208244  0.052141 -1.437344  0.850202   
42846 -0.267781 -0.257309 -0.040751  0.221674 -0.677453 -0.215137  0.127825   
12294  0.365243  0.411186 -0.583382 -2.530445 -1.901641 -2.115818  1.432459   
6515   0.806328 -1.792068 -0.365371 -2.191827 -1.053690 -3.125303  1.867808   
28951  1.289828  1.016248 -1.290872 -0.930182 -0.037441 -0.703731  0.780612   
33175 -1.816250  1.033012  0.541161  0.586694  0.404598  1.382395 -0.744737   
28608 -0.210318  2.522772  1.241508  1.632014 -0.424316  3.961414 -3.025979   
25327  1.801356  0.210682  0.349412  0.799560  0.255603  1.427280 -1.278756   
10943  0.396698 -0.922206  0.463048 -0.312719 -0.618536 -0.647234 -0.118673   
6269   0.156219  2.083855  0.493973 -0.585030  2.209349  1.927059 -1.242466   
24099 -0.821824 -0.090092  1.110707  0.091105  0.364888  0.739670 -0.849963   
23394  0.025718 -0.053296 -0.634326  0.903412 -0.076133 -0.1249

In [3]:
rar_data = pd.concat([X_train, y_train], axis=1)

In [5]:
data2 = pd.DataFrame(data=np.arange(len(rar_data)), index=rar_data.index)

In [8]:
len(rar_data)

60123

In [4]:
target = 'Col174'
rar = wrar.rar.RaR(rar_data)


In [ ]:
rar.run(target, k=5, runs=200)

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier()
clf.fit(data.drop('Col174', axis=1), data['Col174'])


In [ ]:
ranking = []
for index, importance in enumerate(clf.feature_importances_):
    ranking.append((data.columns[index], importance))
ranking.sort(key=lambda r: r[1], reverse=True)
for (index, rank) in enumerate(ranking):
        print('{}. {} with a score of {}'.format(index + 1, rank[0], rank[1]))